service: lambda
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.9

functions:
  fetch_menus:
    handler: handler.handler_fetch_menus
    environment:
      AUTH_REGION: ${env:AUTH_REGION}
      AUTH_USER_POOL_ID: ${env:AUTH_USER_POOL_ID}
      AUTH_CRIENT_ID: ${env:AUTH_CRIENT_ID}
    events:
      - http:
          path: "/menus/fetch"
          method: "get"
  
  init_toread:
    handler: handler.handler_init_toread
    environment:
      AUTH_REGION: ${env:AUTH_REGION}
      AUTH_USER_POOL_ID: ${env:AUTH_USER_POOL_ID}
      AUTH_CRIENT_ID: ${env:AUTH_CRIENT_ID}
    events:
      - http:
          path: "/toread/init"
          method: "get"

        
plugins:
  - serverless-offline
  - serverless-python-requirements